name: Db-Connector CI
on: [push, pull_request]
jobs:
  db-connector:
    name: Db-Connector
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
    strategy:
      fail-fast: true
      matrix:
#        php-versions: ['7.1', '7.2', '7.3', '7.4']
        php-versions: ['7.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Test MySQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -ppassword -e "SHOW DATABASES"

      - name: Validate Composer .json and .lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Code sniffer
        run: vendor/bin/phpcs

      - name: PHPStan
        run: vendor/bin/phpstan analyze -c $GITHUB_WORKSPACE/phpstan.neon

      - name: PHPUnit
        run: vendor/bin/phpunit -c $GITHUB_WORKSPACE/phpunit.xml --coverage-text
        env:
          FUNC_TEST_ENV_FILE: .env.test
